# Generated by Django 4.2 on 2023-06-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_doctor_special_alter_operation_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('experience', models.CharField(choices=[('Select Experience', 'Select Experience'), ('2 years', '2 years'), ('3 years', '3 years'), ('4 years', '4 years'), ('5 years', '5 years'), ('More than', 'More than')], default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.nurse')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.operation')),
            ],
        ),
    ]
