# Generated by Django 4.2 on 2023-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_nurse_nurse_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse_list',
            name='odate',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='nurse_list',
            name='otime',
            field=models.TimeField(default=''),
        ),
    ]
