# Generated by Django 4.2 on 2023-06-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_nurse_list_odate_nurse_list_otime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse_list',
            old_name='odate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='nurse_list',
            old_name='otime',
            new_name='time',
        ),
    ]
