# Generated by Django 4.2 on 2023-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_rename_odate_nurse_list_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse_list',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nurse_list',
            name='time',
            field=models.TimeField(),
        ),
    ]
