# Generated by Django 4.2 on 2023-06-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_remove_nurse_list_date_remove_nurse_list_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse_list',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='nurse_list',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
