# Generated by Django 4.2 on 2023-06-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_nurse_list_date_nurse_list_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse_list',
            name='date',
        ),
        migrations.RemoveField(
            model_name='nurse_list',
            name='time',
        ),
    ]
